### PR TITLE
Alex test cases done

### PR DESCRIPTION
**Pull request by olek-pas**
Work is done and waiting for confirmation

### CODE REVIEW

**Comment by OlgaGrynyk** [comment]
good job

**Review by Jewel522 — COMMENTED** [review]
Well done! Add more comments and I will review one more time!

**Review by OlgaGrynyk — APPROVED** [review]
great work Alex

**Review by nilufarmirzoeva — COMMENTED** [review]
good job

**Comment by nilufarmirzoeva** [comment]
Good job everyone

**Comment by OlgaGrynyk** [comment]
You need to review and approve

**Review by OlgaGrynyk — APPROVED** [review]
great

**Comment by olek-pas** [comment]
Thank you guys, if you like my code please approve it

**Review by nilufarmirzoeva — APPROVED** [review]

**Review by Jewel522 — APPROVED** [review]
Fantastic job!

**Comment by Jewel522** [comment]
Nice one!

**Pull request merged**
